# Generated by Django 5.0.3 on 2024-03-16 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_meal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
